name: API
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.28.1"
      - name: Buf Linter
        uses: bufbuild/buf-lint-action@v1
        with:
          input: "api"
      - name: Buf Breaking Change Check
        uses: bufbuild/buf-breaking-action@v1
        with:
          input: "api"
          against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main,subdir=api"
