name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
     - master
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          check-latest: true
      - name: Run Build-Pipeline
        uses: dagger/dagger-for-github@v5
        with:
          verb: run
          args: go run ci/main.go -cmd "go build -o output/ ./cmd/example/main.go"
          version: "0.9.3"
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: output
